### ISSUE TITLE
sm2加解密问题

### ISSUE THREAD

**Issue by iotyib** [Saroth/smbedtls#1]
每次sm2解密后的密文结果应该是不一样的吧？

**Comment by Saroth** [comment]
同样的数据, sm2每次加密的密文都不一样, 且都能正确解密.
因为计算过程使用了随机数. 
计算流程可参考:GM-T 0003.4-2012 SM2椭圆曲线公钥密码算法 第4部分：公钥加密算法: 6.2 加密算法流程.

**Comment by iotyib** [comment]
但是我调用sm2.c文件里mbedtls_sm2_self_test函数，每次产生的密文都是一样的，明文改变后密文结果还是不变，请问是我少调了什么函数吗？

**Comment by Saroth** [comment]
mbedtls_sm2_self_test函数，实现的是标准文档中官方提供的示例计算流程，数据也完全一致。
所以随机数也是使用了标准文档的固定数值：sm2_test1_rand_fix、sm2_test2_rand_fix

**Comment by iotyib** [comment]
您好，这是我两次不同明文加密之后的结果：
plain_text:
656e6372797074696f6e207374616e64656e6372797074696f6e207374616e64
enc:
4245c26fb68b1ddddb12c4b6bf9f2b6d5fe60a383b0d18d1c4144abf17f6252e776cb9264c2a7e88e52b1993fdc47378f65e36811f5c07423a24b8440f1b8

plain_text:
1c4144abf17f6252e776cb9264c2a7e88e52b1993fdc47378f65e36811f5c0
enc:
4245c26fb68b1ddddb12c4b6bf9f2b6d5fe60a383b0d18d1c4144abf17f6252e776cb9264c2a7e88e52b1993fdc47378f65e36811f5c07423a24b8440f1b8

这是我从mbedtls_sm2_self_test函数里拿出来的加密函数，是不是我的调用方式有问题啊？
void sm2_test(void)
{
	int ret = 0;
	unsigned char input[32] = { 0x1C, 0x41, 0x44, 0xAB, 0xF1, 0x7F, 0x62, 0x52,
								0xE7, 0x76, 0xCB, 0x92, 0x64, 0xC2, 0xA7, 0xE8,
								0x8E, 0x52, 0xB1, 0x99, 0x03, 0xFD, 0xC4, 0x73,
								0x78, 0xF6, 0x05, 0xE3, 0x68, 0x11, 0xF5, 0xC0 };
	unsigned char out[64];
	int outlen;
	int i;
	unsigned char sm2_test1_rand_fix[] = {
		0x4C, 0x62, 0xEE, 0xFD, 0x6E, 0xCF, 0xC2, 0xB9,
		0x5B, 0x92, 0xFD, 0x6C, 0x3D, 0x95, 0x75, 0x14,
		0x8A, 0xFA, 0x17, 0x42, 0x55, 0x46, 0xD4, 0x90,
		0x18, 0xE5, 0x38, 0x8D, 0x49, 0xDD, 0x7B, 0x4F };
	mbedtls_sm2_context ctx;
	mbedtls_sm2_init(&ctx);
	ret = mbedtls_ecp_group_load(&ctx.grp, MBEDTLS_ECP_DP_SM2P256T1);
	ret = mbedtls_sm2_encrypt(&ctx, MBEDTLS_MD_SM3, input, 32, out, &outlen, sm2_set_fix_rng, (void *)sm2_test1_rand_fix);
	printf("plain_text:\r\n");
	for (i = 0;i < sizeof(input);i++)
	{
		printf("%x", input[i]);
	}
	printf("\r\nenc:\r\n");
	for (i = 0;i < outlen;i++)
	{
		printf("%x", out[i]);
	}
	getchar();
}

**Comment by Saroth** [comment]
**你的密文数据可能没输出完整**。

### 密文结构
在使用推荐密钥的情况下，sm2的密文长度是明文长度 + 97字节。
结构是``04 | C1 | C2 | C3``：
-   C1：坐标计算数据。长度是密钥位数 / 8 * 2。当前的测试密钥和推荐密钥都是256bit，所以长度是64byte。
-   C2：密文。长度同明文。
-   C3：SM3摘要值。长度32byte。

### 以下是我的计算结果。
#### plain text1:                                          
```hex
 000: 65 6e 63 72 79 70 74 69 6f 6e 20 73 74 61 6e 64
 010: 61 72 64                                                                                         
```
cipher text1:                                         
```hex
 000: 04 24 5c 26 fb 68 b1 dd dd b1 2c 4b 6b f9 f2 b6
 010: d5 fe 60 a3 83 b0 d1 8d 1c 41 44 ab f1 7f 62 52
 020: e7 76 cb 92 64 c2 a7 e8 8e 52 b1 99 03 fd c4 73
 030: 78 f6 05 e3 68 11 f5 c0 74 23 a2 4b 84 40 0f 01
 040: b8 65 00 53 a8 9b 41 c4 18 b0 c3 aa d0 0d 88 6c
 050: 00 28 64 67 9c 3d 73 60 c3 01 56 fa b7 c8 0a 02
 060: 76 71 2d a9 d8 09 4a 63 4b 76 6d 3a 28 5e 07 48
 070: 06 53 42 6d                                    
```

#### plain text2:                                          
```hex
 000: 1c 41 44 ab f1 7f 62 52 e7 76 cb 92 64 c2 a7 e8
 010: 8e 52 b1 99 03 fd c4 73 78 f6 05 e3 68 11 f5 c0
```

cipher text2:                                         
```hex
 000: 04 24 5c 26 fb 68 b1 dd dd b1 2c 4b 6b f9 f2 b6
 010: d5 fe 60 a3 83 b0 d1 8d 1c 41 44 ab f1 7f 62 52
 020: e7 76 cb 92 64 c2 a7 e8 8e 52 b1 99 03 fd c4 73
 030: 78 f6 05 e3 68 11 f5 c0 74 23 a2 4b 84 40 0f 01
 040: b8 1c 2f 74 71 13 4e d2 23 38 db 41 31 1d 2b a5
 050: 8c c7 44 b2 20 3c 3f 14 c1 8e ba 35 c2 8a 2d 99
 060: 08 77 97 9d 54 10 b9 e5 db b1 e4 55 12 40 5b 8f
 070: 32 ca 80 c2 67 6c 2c b9 c0 91 19 25 fa 8e 70 56
 080: 45                                             
```

**Comment by SuitTY** [comment]
您好关于密文排序C1 C2 C3 怎么修改为C1 C3 C2

**Comment by Saroth** [comment]
> 您好关于密文排序C1 C2 C3 怎么修改为C1 C3 C2

以前我的做法是，接口返回密文后，再按应用需求调整密文结构。
如果应用场景只需要c132的结构，建议直接调整下接口mbedtls_sm2_encrypt和mbedtls_sm2_decrypt
