### ISSUE TITLE
bugfix

### ISSUE THREAD

**Issue by enterpriseZ** [Saroth/smbedtls#3]
在文件
[smbedtls](https://github.com/Saroth/smbedtls)/[library](https://github.com/Saroth/smbedtls/tree/mbedtls-2.1.12-sm/library)/sm2.c
第426行，
在使用mbedtls_mpi_init(&t);之前应该调用mbedtls_mpi_free(&t);函数，否则会有严重的内存泄漏问题，望修复，谢谢。

**Comment by Saroth** [comment]
@enterpriseZ 感谢反馈。
这个仓库已经很久没维护了。
刚看了官方最新3.3.0版本，仍然没有支持国家商密算法……
